name: Create Cypress report
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        env:
          CYPRESS_COMMIT_HASH: ${{ github.sha }}
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir -p public/videos
          cp -r cypress/videos public/videos

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate
        env:
          CYPRESS_COMMIT_HASH: ${{ github.sha }}

      - name: Create commit-specific directory
        run: mkdir -p public/${{ github.sha }}

      - name: Copy report files to commit-specific directory
        run: |
          cp -r public/* public/${{ github.sha }}
          rm -rf public/${{ github.sha }}/version

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'Rahul Kundu'
          user_email: 'rahulkundu2016@gmail.com'
