name: Create Cypress report

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests and generate report
        run: npm run generate:report
        continue-on-error: true

      - name: Set up Git
        run: |
          git config --global user.name 'Rahul Kundu'
          git config --global user.email 'rahulkundu2016@gmail.com'

      - name: Fetch existing gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages

      - name: Copy reports to gh-pages
        run: |
          mkdir -p gh-pages
          cp -r public/all-reports/* gh-pages/
          cp -r gh-pages/* public/all-reports/

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/all-reports
          user_name: 'Rahul Kundu'
          user_email: 'rahulkundu2016@gmail.com'
