name: Create Cypress report
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest
    env:
      REPORT_DIR: report-${{ github.run_number }}-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Prepare report directory
        run: |
          mkdir $REPORT_DIR
          cp -r cypress/results/json $REPORT_DIR

      - name: Commit and push report to gh-pages branch
        run: |
          git config --global user.email "rahulkundu2016@gmail.com"
          git config --global user.name "Rahul Kundu"
          git add .
          git commit -m "Update Cypress report"
          git push origin HEAD:gh-pages
