name: Create Cypress report
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install a project with a clean slate
        run: |
          yarn install

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Create unique artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report-${{ github.run_id }}
          path: public

  deploy:
    name: Deploy report page
    runs-on: ubuntu-latest
    needs: cypress-e2e-chrome81
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cypress-report-${{ github.run_id }}
          path: public

      - name: Rename folder with unique run id
        run: mv public run${{ github.run_id }}

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'Rahul Kundu'
          user_email: 'rahulkundu2016@gmail.com'
          publish_branch: gh-pages