name: Create Cypress report

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests and generate report
        run: |
          # Run Cypress tests and generate the report
          npx cypress run --reporter mochawesome || true
          # Create a new report directory based on current date/time
          mkdir -p public/report$(date +%s)

      - name: Set up Git
        run: |
          git config --global user.name 'Rahul Kundu'
          git config --global user.email 'rahulkundu2016@gmail.com'

      - name: Fetch existing gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages || true

      - name: Clean up existing report directory
        run: |
          rm -rf gh-pages/*

      - name: Copy new report to gh-pages
        run: |
          # Find the latest report directory
          latest_report=$(ls -td public/report* | head -n 1)
          # Copy the latest report directory to gh-pages
          cp -r $latest_report/* gh-pages/ || true

      - name: Push updates to gh-pages
        run: |
          git add .
          git commit -m "Add latest report" || true
          git push origin gh-pages || true
