name: Create Cypress report
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install a project with a clean slate
        run: |
          yarn install --frozen-lockfile
          $(yarn bin)/cypress cache path
          $(yarn bin)/cypress cache list
          $(yarn bin)/cypress verify

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir -p public
          cp -r cypress/videos public/videos

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Create unique directory for each run in gh-pages branch
        run: |
          unique_dir="public/run-$(date +'%Y%m%d_%H%M%S')_${{ github.run_number }}"
          mkdir -p "$unique_dir"
          mv public/* "$unique_dir"/
          git checkout gh-pages
          mkdir -p temp_public
          mv ../public/* temp_public/ || true
          mv temp_public/* .
          rm -rf temp_public
          git add .
          git commit -m "Add report for run ${{ github.run_number }}"
          git push

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'Rahul Kundu'
          user_email: 'rahulkundu2016@gmail.com'
