name: Create Cypress report

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests and generate report
        run: npm run generate:report
        continue-on-error: true

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/all-reports
          user_name: 'Rahul Kundu'
          user_email: 'rahulkundu2016@gmail.com'
