name: Create Cypress report

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 1-31 * *'
  workflow_dispatch:

jobs:
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir -p ${{ github.run_id }}/videos
          cp -r cypress/videos ${{ github.run_id }}/videos
        continue-on-error: true

      - name: Merge test results into one
        run: npm run report:merge
        continue-on-error: true

      # Manually write the report:generate step with run_id
      - name: Generate HTML report
        run: marge index.json --reportDir ${{ github.run_id }} --assetsDir ${{ github.run_id }}/assets --reportPageTitle index.html
        continue-on-error: true

      - name: Set up Git
        run: |
          git config --global user.name 'Rahul Kundu'
          git config --global user.email 'rahulkundu2016@gmail.com'

      - name: Fetch existing gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages || git checkout -b gh-pages

      # - name: Copy new report to gh-pages
      #   run: |
      #     cp -r ${{ github.run_id }}/* .

      - name: Commit changes
        run: |
          git add .
          git commit -m "Add report for run ${{ github.run_id }}" || true
          git push origin gh-pages || true
